#!/usr/bin/env node
/**
 * Plugin Auto-Discovery Script
 *
 * Automatically discovers all plugins in the plugins/ directory and generates
 * the plugins/index.ts file with imports. This makes the plugin system truly
 * dynamic - just add or remove plugin directories and they're automatically
 * registered.
 *
 * Run this script:
 * - Manually: node scripts/discover-plugins.js
 * - Automatically: Before build (in package.json)
 */

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PLUGINS_DIR = join(process.cwd(), "plugins");
const OUTPUT_FILE = join(PLUGINS_DIR, "index.ts");

/**
 * Discover all plugin directories
 */
function discoverPlugins() {
  const entries = readdirSync(PLUGINS_DIR);

  const plugins = entries.filter((entry) => {
    // Skip special directories and files
    if (
      entry.startsWith("_") ||
      entry.startsWith(".") ||
      entry === "index.ts" ||
      entry === "registry.ts"
    ) {
      return false;
    }

    // Only include directories
    const fullPath = join(PLUGINS_DIR, entry);
    try {
      return statSync(fullPath).isDirectory();
    } catch {
      return false;
    }
  });

  return plugins.sort();
}

/**
 * Generate the plugins/index.ts file
 */
function generateIndexFile(plugins) {
  const imports = plugins.map((plugin) => `import "./${plugin}";`).join("\n");

  const content = `/**
 * Plugins Index (Auto-Generated)
 * 
 * This file is automatically generated by scripts/discover-plugins.js
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 * 
 * To add a new integration:
 * 1. Create a new directory in plugins/ (e.g., plugins/my-integration/)
 * 2. Add your plugin files (index.tsx, steps/, codegen/, etc.)
 * 3. Run: pnpm discover-plugins (or it runs automatically on build)
 * 
 * To remove an integration:
 * 1. Delete the plugin directory
 * 2. Run: pnpm discover-plugins (or it runs automatically on build)
 * 
 * Discovered plugins: ${plugins.join(", ") || "none"}
 */

${imports || "// No plugins discovered"}

export type { IntegrationPlugin } from "./registry";

// Export the registry utilities
export {
  findActionById,
  getActionsByCategory,
  getAllActions,
  getAllIntegrations,
  getIntegration,
  getIntegrationLabels,
  getIntegrationTypes,
  getSortedIntegrationTypes,
  registerIntegration,
} from "./registry";
`;

  writeFileSync(OUTPUT_FILE, content, "utf-8");
}

/**
 * Main execution
 */
function main() {
  console.log("🔍 Discovering plugins...");

  const plugins = discoverPlugins();

  if (plugins.length === 0) {
    console.log("⚠️  No plugins found in plugins/ directory");
  } else {
    console.log(`✅ Found ${plugins.length} plugin(s):`);
    for (const plugin of plugins) {
      console.log(`   - ${plugin}`);
    }
  }

  console.log("\n📝 Generating plugins/index.ts...");
  generateIndexFile(plugins);

  console.log("✨ Done! Plugin registry updated.\n");
}

main();
